language: bash
services: docker
before_install:
  - cd RestWithSpringBootUdemyDocker
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push leolimasjc/mysql-rest-with-spring-boot-udemy;
    docker push leolimasjc/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false
